name:       json-poll-and-set-redis
version:    0.1.0
github:     "ketzacoatl/json-poll-and-set-redis"
license:    "BSD3"
author:     "Ketzacoatl"
maintainer: "ketzacoatl"
copyright:  "(c) 2018 Contributors"

extra-source-files:
  - LICENSE
  - README.md

synopsis:    "haskell demo: poll a JSON API, extract value, and set a key in redis"
description: "There isn't more to say than that.. really."

dependencies:
  - aeson
  - attoparsec
  - base >=4.3 && <5
  - bytestring
  - conduit
  - conduit-extra
  - hedis
  - http-conduit
  - http-client
  - http-client-tls
  - http-types
  - monad-control
  - monad-logger
  - text

library:
  source-dirs: src

executables:
  json-poll-and-set-redis:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - json-poll-and-set-redis


